export { default as Landing } from './Landing'
export { default as Home } from './Home'
export { default as List } from './List'
export { default as Detail } from './Detail'
export { default as Passport } from './Passport'
export { default as CreateRoute } from './CreateRoute'
export { default as ReadDetail } from './ReadDetail'
